storage:
  backend: s3
  s3:
    bucket_name: ${S3_BUCKET}
    endpoint: s3.${AWS_REGION}.amazonaws.com
    region: ${AWS_REGION}
    prefix: pyroscope/

self_profiling:
  disable_push: true

limits:
  max_label_names_per_series: 30
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32

server:
  http_listen_port: 4040
