storage:
  backend: s3
  prefix: __PYROSCOPE_STORAGE_PREFIX__
  s3:
    bucket_name: __BUCKET_NAME__
    endpoint: s3.__AWS_REGION__.amazonaws.com
    region: __AWS_REGION__

self_profiling:
  disable_push: true

limits:
  max_label_names_per_series: 30
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32

server:
  http_listen_port: 4040
