apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: default
  labels:
    app.kubernetes.io/name: tempo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
      targetPort: 3200
      protocol: TCP
    - name: otlp-grpc
      port: 4320
      targetPort: 4320
      protocol: TCP
    - name: otlp-http
      port: 4321
      targetPort: 4321
      protocol: TCP
  selector:
    app.kubernetes.io/name: tempo
