apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pyroscope-ebpf
  namespace: default
  labels:
    app.kubernetes.io/name: pyroscope-ebpf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pyroscope-ebpf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pyroscope-ebpf
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      containers:
        - name: pyroscope-ebpf
          image: grafana/pyroscope-ebpf:0.4.0
          args:
            - --config.file=/etc/pyroscope-ebpf/config.yaml
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: cluster_name
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
              cpu: 50m
          volumeMounts:
            - name: config
              mountPath: /etc/pyroscope-ebpf
              readOnly: true
            - name: sys-kernel
              mountPath: /sys/kernel
              readOnly: true
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
            - name: proc
              mountPath: /proc
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: pyroscope-ebpf-config
        - name: sys-kernel
          hostPath:
            path: /sys/kernel
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
        - name: proc
          hostPath:
            path: /proc
