apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
  namespace: default
  labels:
    app.kubernetes.io/name: beyla
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: beyla
  template:
    metadata:
      labels:
        app.kubernetes.io/name: beyla
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      containers:
        - name: beyla
          image: grafana/beyla:1.8.4
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: cluster_name
            - name: BEYLA_CONFIG_PATH
              value: /etc/beyla/beyla-config.yaml
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 9400
              hostPort: 9400
              protocol: TCP
              name: metrics
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
              cpu: 50m
          volumeMounts:
            - name: config
              mountPath: /etc/beyla
              readOnly: true
            - name: sys-kernel
              mountPath: /sys/kernel
              readOnly: true
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
            - name: proc
              mountPath: /proc
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: beyla-config
        - name: sys-kernel
          hostPath:
            path: /sys/kernel
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
        - name: proc
          hostPath:
            path: /proc
