apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: ebpf-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ebpf-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ebpf-exporter
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      containers:
        - name: ebpf-exporter
          image: cloudflare/ebpf_exporter:v2.4.2
          args:
            - --config.dir=/etc/ebpf_exporter
            - --web.listen-address=0.0.0.0:9435
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 9435
              hostPort: 9435
              protocol: TCP
              name: metrics
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
              cpu: 25m
          volumeMounts:
            - name: config
              mountPath: /etc/ebpf_exporter
              readOnly: true
            - name: sys-kernel
              mountPath: /sys/kernel
              readOnly: true
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: kernel-src
              mountPath: /usr/src
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: ebpf-exporter-config
        - name: sys-kernel
          hostPath:
            path: /sys/kernel
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
        - name: proc
          hostPath:
            path: /proc
        - name: modules
          hostPath:
            path: /lib/modules
        - name: kernel-src
          hostPath:
            path: /usr/src
